name: Pre-merge checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -e . pycodestyle pytest

      - name: Run pycodestyle
        run: make stylecheck
  pytest:
    strategy:
      matrix:
        python_version: ['3.6', '3.7',  '3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    container: python:${{ matrix.python_version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -e . pycodestyle pytest

      - name: Run pytest
        run: make test
